In [1]:
import pandas as pd
sample_data = {'name': ['John', 'Alia', 'Ananya','Steve','vish'],
               'gender': ['M','F','F','M','M'],
               'communication_skill_score': [40,45,23,39,39],
               'quantative_skill_score':[38,41,42,48,32]}
data = pd.DataFrame(sample_data)
data

     name gender  communication_skill_score  quantative_skill_score
0    John      M                         40                      38
1    Alia      F                         45                      41
2  Ananya      F                         23                      42
3   Steve      M                         39                      48
4    vish      M                         39                      32

In [3]:
print('Mean of Communication skill score: ',data['communication_skill_score'].mean())
print('Mean of Quantative skill score:',data['quantative_skill_score'].mean())

Mean of Communication skill score:  37.2
Mean of Quantative skill score: 40.2

In [4]:
print('Mode of Communication skill score: ', data['communication_skill_score'].mode())
print('Mode of Quantitative skill score: ', data['quantative_skill_score'].mode())

Mode of Communication skill score:  0    39
Name: communication_skill_score, dtype: int64
Mode of Quantitative skill score:  0    32
1    38
2    41
3    42
4    48
Name: quantative_skill_score, dtype: int64

In [5]:
print('Median of Communication skill score: ', data['communication_skill_score'].median())
print('Median of Quantitative skill score: ', data['quantative_skill_score'].median())

Median of Communication skill score:  39.0
Median of Quantitative skill score:  41.0

In [6]:
q1 = data['communication_skill_score'].quantile(.25)
q3 = data['communication_skill_score'].quantile(.75)
iqr = q3 - q1
print('Inter Quartile Range of Communication skill score: ', iqr)

Inter Quartile Range of Communication skill score:  1.0

In [7]:
communication_skill_range = data['communication_skill_score'].max() - data['communication_skill_score'].min()
quantative_skill_range = data['quantative_skill_score'].max() - data['quantative_skill_score'].min()
print('Range of Communication skill score: ', communication_skill_range)
print('Range of Quantative skill score: ', quantative_skill_range)

Range of Communication skill score:  22
Range of Quantative skill score:  16

In [8]:
communication_skill_variance = data['communication_skill_score'].var()
quantative_skill_variance = data['quantative_skill_score'].var()
print('Variance of Communication skill score: ', communication_skill_variance)
print('Variance of Quantative skill score: ', quantative_skill_variance)

Variance of Communication skill score:  69.2
Variance of Quantative skill score:  34.2

In [9]:
communication_skill_std = data['communication_skill_score'].std()
quantative_skill_std = data['quantative_skill_score'].std()
print('Standard Deviation of Communication skill score: ', communication_skill_std)
print('Standard Deviation of Quantative skill score: ', quantative_skill_std)

Standard Deviation of Communication skill score:  8.318653737234168
Standard Deviation of Quantative skill score:  5.848076606885378

In [10]:
data.describe()

       communication_skill_score  quantative_skill_score
count                   5.000000                5.000000
mean                   37.200000               40.200000
std                     8.318654                5.848077
min                    23.000000               32.000000
25%                    39.000000               38.000000
50%                    39.000000               41.000000
75%                    40.000000               42.000000
max                    45.000000               48.000000

In [11]:
communication_skill_kurt = data['communication_skill_score'].kurtosis()
quantative_skill_kurt = data['quantative_skill_score'].kurtosis()
print('Kurtosis of Communication skill score: ', communication_skill_kurt)
print('Kurtosis of Quantative skill score: ', quantative_skill_kurt)

Kurtosis of Communication skill score:  3.6010641852384015
Kurtosis of Quantative skill score:  0.8243562121678494

In [15]:
# Covariance of data
print('Covariance of Communication skill score and Quantative skill score: ', data['communication_skill_score'].cov(data['quantative_skill_score']))
print('Covariance of Quantative skill score and Communication skill score: ', data['quantative_skill_score'].cov(data['communication_skill_score']))

Covariance of Communication skill score and Quantative skill score:  -6.55
Covariance of Quantative skill score and Communication skill score:  -6.55

In [20]:
# Corelation of communication skill score
print('Corelation of Communication skill score and Quantative skill score: ', data['communication_skill_score'].corr(data['quantative_skill_score']))

Corelation of Communication skill score and Quantative skill score:  -0.1346403400203736